sudo: false
language: c
env:
  global:
  - SHADOWSOCKS_LIBEV_VERSION=3.1.3
  matrix:
  - TOOLCHAIN=mipsel
  - TOOLCHAIN=arm
cache:
  directories:
  - "$HOME/CACHE"
script: make package TOOLCHAIN=${TOOLCHAIN} SHADOWSOCKS_LIBEV_VERSION=${SHADOWSOCKS_LIBEV_VERSION} SHADOWSOCKS_LIBEV_RELEASE_VERSION=${TRAVIS_TAG:-"${SHADOWSOCKS_LIBEV_VERSION}-${TRAVIS_COMMIT:0:8}"} CACHEROOT="${HOME}/CACHE" SHADOWSOCKS_LIBEV_TARGET_DIR="${HOME}"
after_script: rm -rf /tmp/*
deploy:
  provider: releases
  api_key:
    secure: hTyjtsmGS48PQ5hXM6qe3J8pLsndgMiOZn4LDyJE+ZJItJk2mhG/zPwDFu5QiqGk7Mi4GjXMMEIRfaczbEn+CYGdiBYIV7YXjjWKuzdX2/xiGBi0+EjEMlLqzkO+Xr7ova9/S6QNR7PeyrYVj5XNORhkk2evtfgBK7UgoYzOt+g2aqu32qF0Eq7/KjOWKn0b89aq05GA9pICO+5LhvPmYNvaWRumXLzVEbDZ/Ey27iNFMtUCx2YIXRc3iBKL2bcYbA9yuYD1e39PMCGhoLzDpSJ6yW0dm64uweooz7ziqp60TPs45X+RnpN29/cRO/3yEh05Qu7pkj9TqIsI+fP6lQXypMQ3KS6cdmlV0e23g7xlFVkcfGbTXR4nbXvsV06aO4gEHvAN7bl8710kPZubShj939STvoXN83/AdUF/k6GL6X2FgozdQevjDn+mM744897naKS76KRF7SxsRkKIWOO4Xaomf3A9RwZ5B2iqxHKtqCxbazRW0Tl8ZLs534lZVDHz75EMBZqDoawuqhGwKBEbfbVwBY5ogsgTTajgT5RXd42jTO8IG+0P14NF7gdQ1TAf7InUoqkiLXY5OXtWJB6TLDmX80rfxjxNHzkt/t9BgYur9QrhHgHZTlRT/rDIXjldXgQVMXQwmuVNbyR563q2qVE1wBCpR+rZ1Fa5bnQ=
  file:
  - "${HOME}/shadowsocks-libev-${TRAVIS_TAG}-${TOOLCHAIN}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
  body: |+
    - Shadowsocks-libev: ${SHADOWSOCKS_LIBEV_VERSION}
    - Build: [#${TRAVIS_BUILD_NUMBER}](https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_BUILD_ID})"
    - NOTICE: Checksum list is in the build log.

addons:
  apt:
    packages:
    - autoconf
    - automake
    - bison
    - bzip2
    - diffutils
    - flex
    - m4
    - build-essential
    - gawk
    - groff-base
    - libtool
    - libslang2
    - make
    - patch
    - perl
    - pkg-config
    - shtool
    - texinfo
    - zlib1g-dev
    - gettext
    - libexpat1-dev
    - libssl-dev
    - gperf
    - python
    - libxml-parser-perl
    - gcc-multilib
    - libxml2-dev
    - g++-4.4
    - g++-multilib
    - libncurses5-dev
    - libstdc++6-4.4-dev
    - libvorbis-dev
    - g++-4.4-multilib
    - autopoint
    - autogen
    - sed
    - intltool
    - libelf1:i386
    - libglib2.0-dev
    - lib32z1-dev
    - lib32stdc++6
    - wget
