TMPDIR ?= $(shell dirname $(shell mktemp -u))
NPROCS ?= $(shell nproc)
PACKAGE_NAME := shadowsocks-libev

DEPSROOT = $(TMPDIR)/$(PACKAGE_NAME)/deps
GIT_REPO = $(DEPSROOT)/git
TARGET_DIR = $(TMPDIR)/$(PACKAGE_NAME)/build

VERSION := nightly
RELEASE_VERSION = $(VERSION)

PACKAGE = $(PACKAGE_NAME)-$(RELEASE_VERSION)-$(BUILD_ARCH)
PACKAGE_PATH = $(TARGET_DIR)/$(SHADOWSOCKS_LIBEV)
PACKAGE_TARBALL = $(PACKAGE_FILENAME).tar.gz
